package com.star_pick.starpick.support;

import com.star_pick.starpick.domain.cooking.domain.CookHistory;
import com.star_pick.starpick.domain.cooking.repository.CookHistoryRepository;
import com.star_pick.starpick.domain.ingestion.repository.IngestionJobRepository;
import com.star_pick.starpick.domain.recipe.domain.Recipe;
import com.star_pick.starpick.domain.recipe.domain.RecipeCategory;
import com.star_pick.starpick.domain.recipe.domain.RecipeIngredient;
import com.star_pick.starpick.domain.recipe.domain.RecipeStep;
import com.star_pick.starpick.domain.recipe.repository.RecipeRepository;
import com.star_pick.starpick.domain.upload.domain.UploadPurpose;
import com.star_pick.starpick.domain.upload.service.AttachOutcome;
import com.star_pick.starpick.domain.upload.repository.UploadObjectRepository;
import com.star_pick.starpick.domain.upload.service.UploadService;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 여러 통합 테스트가 함께 쓰는 데이터 픽스처.
 *
 * <p>Recipe 테스트 3개가 각자 같은 헬퍼를 들고 있었고 Cooking 테스트가 같은 것을 또 필요로 해서
 * 여기로 모았다. 한 곳에서만 쓰는 헬퍼는 옮기지 않는다 — 간접 계층만 늘어난다.
 *
 * <p>{@code @IntegrationTest} 가 직접 import 한다. <b>{@code TestcontainersConfiguration} 에 두면
 * 안 된다</b> — 이유는 그 클래스의 javadoc 에 있다.
 */
@RequiredArgsConstructor
public class TestFixtures {

    private final UploadService uploadService;

    private final IngestionJobRepository ingestionJobRepository;

    private final FakeObjectStorage objectStorage;

    private final RecipeRepository recipeRepository;

    private final UploadObjectRepository uploadObjectRepository;

    private final CookHistoryRepository cookHistoryRepository;

    private final JdbcTemplate jdbcTemplate;

    /**
     * 테스트 사이의 데이터를 비운다.
     *
     * <p>실제로 필요한 테이블만 골라 지우지 않고 항상 전부 지운다. 어떤 테스트가 어떤 테이블을
     * 남기는지는 나중에 바뀌는데, 그때 지우는 목록을 갱신하지 않으면 테스트 간 오염이 조용히 생긴다.
     *
     * <p><b>재료 마스터는 여기서 건드리지 않는다.</b> 이 메서드는 테스트가 만든 행을 지우는 것이고,
     * 마스터는 migration 이 넣은 공유 시드라 지우면 안 된다. 시드를 일시적으로 바꾼 테스트는
     * {@link #restoreIngredientActivity()} 로 되돌린다.
     */
    public void reset() {
        // 2단계에서 recipe.ingestion_job_id FK가 생기면 recipe 삭제 다음으로 옮긴다.
        ingestionJobRepository.deleteAll();
        cookHistoryRepository.deleteAll();
        recipeRepository.deleteAll();
        uploadObjectRepository.deleteAll();
        objectStorage.clear();
    }

    /**
     * {@code active} 를 바꾼 테스트가 공유 시드를 원래대로 되돌린다.
     *
     * <p>{@code @IntegrationTest} 가 JVM 전체에서 PostgreSQL 컨테이너 하나를 공유하므로, 비활성으로
     * 바꾼 채 끝나면 이후 다른 클래스의 테스트가 순서에 따라 깨진다. 오염을 만든 클래스가
     * {@code @AfterEach} 에서 호출한다.
     *
     * <p>{@code where active = false} 로 좁힌 것은 이미 활성인 행까지 매번 다시 쓰지 않기 위해서다.
     */
    public void restoreIngredientActivity() {
        jdbcTemplate.update("update ingredient set active = true where active = false");
    }

    /** 재료 코드로 마스터 id 를 찾는다. 시드 id 는 고정값이 아니라 identity 라 코드로 조회해야 한다. */
    public Long ingredientId(String code) {
        return jdbcTemplate.queryForObject(
                "select id from ingredient where code = ?", Long.class, code);
    }

    /**
     * FK 대상이 되는 임의 userId 를 위해 {@code users} 행을 보장한다.
     *
     * <p>테스트는 {@code jwtProvider.generateTokens(OWNER_ID)} 로 DB 없이 토큰을 발급해왔다.
     * {@code recipe.user_id}/{@code upload_object.user_id} FK 가 생긴 뒤에는 참조 대상 행이
     * 실제로 있어야 한다. {@code user_id} 는 identity 이지만 {@code generated by default} 라
     * 명시적 값 삽입이 허용된다. {@code reset()} 이 {@code users} 는 지우지 않으므로 컨테이너
     * 생애 동안 한 번만 실제로 insert 되고 이후에는 {@code on conflict} 로 아무 일도 하지 않는다.
     *
     * <p>{@code generated by default} 는 명시적 값을 허용할 뿐 시퀀스를 스스로 당기지 않는다.
     * 매번 호출 뒤 시퀀스를 현재 최댓값으로 맞춰서, 이후 JPA 가 만드는 User 의 identity 채번이
     * 이 메서드가 미리 쓴 id 와 충돌하지 않게 한다.
     */
    public void seedUser(Long userId) {
        int inserted = jdbcTemplate.update("""
                insert into users (user_id, service_terms_agreed, privacy_agreed, marketing_agreed,
                                    signup_completed_at, created_at)
                values (?, true, true, true, now(), now())
                on conflict (user_id) do nothing
                """, userId);
        if (inserted > 0) {
            jdbcTemplate.queryForObject("""
                    select setval(pg_get_serial_sequence('users', 'user_id'),
                                  (select max(user_id) from users))
                    """, Long.class);
        }
    }

    /**
     * 발급부터 업로드 완료까지 마친 Key 를 만든다.
     *
     * <p>발급만 해두면 저장소에 파일이 없어 {@code attach} 가 {@code INVALID} 를 돌려준다.
     * "업로드까지 마쳤다"는 상태를 만들려면 {@code putObject} 가 반드시 필요하다.
     */
    public String uploadedKey(Long userId, UploadPurpose purpose) {
        seedUser(userId);
        String objectKey = uploadService.issueUploadUrl(userId, purpose, "image/jpeg").objectKey();
        objectStorage.putObject(objectKey);
        return objectKey;
    }

    /** Key 가 어딘가에 연결됐는지. 연결 성공과 롤백을 확인할 때 쓴다. */
    public boolean isAttached(String objectKey) {
        return uploadObjectRepository.findById(objectKey).orElseThrow().isAttached();
    }

    /** 재료·조리 순서가 없는 최소 Recipe. */
    public Long saveRecipe(Long ownerId) {
        return recipeRepository.save(newRecipe(ownerId)).getId();
    }

    /** 재료 2개와 조리 순서 2개를 가진 Recipe. */
    public Long saveRecipeWithChildren(Long ownerId) {
        Recipe recipe = newRecipe(ownerId);
        recipe.replaceIngredients(List.of(
                RecipeIngredient.of(null, "김치", "1/4포기"),
                RecipeIngredient.of(null, "두부", null)));
        recipe.replaceSteps(List.of(RecipeStep.of("물을 끓인다"), RecipeStep.of("김치를 넣는다")));
        return recipeRepository.save(recipe).getId();
    }

    /**
     * 업로드까지 마친 대표 이미지를 Recipe 에 연결하고 objectKey 를 돌려준다.
     *
     * <p>Recipe 를 통째로 만드는 헬퍼로 두지 않은 이유는, 삭제 테스트가 "커버가 있는 Recipe"와
     * "자식까지 있는 Recipe"를 조합해서 써야 하기 때문이다.
     */
    public String attachCover(Long ownerId, Long recipeId) {
        String objectKey = attachedKey(ownerId, UploadPurpose.RECIPE_COVER);
        Recipe recipe = recipeRepository.findById(recipeId).orElseThrow();
        recipe.changeCoverImage(objectKey);
        recipeRepository.save(recipe);
        return objectKey;
    }

    /** 완성 사진이 연결된 CookHistory 를 만든다. 사진 없는 기록이 필요하면 {@link #saveCookHistory} 를 쓴다. */
    public String saveCookHistoryWithPhoto(Long ownerId, Long recipeId) {
        String photoKey = attachedKey(ownerId, UploadPurpose.COOK_HISTORY_PHOTO);
        cookHistoryRepository.save(CookHistory.create(recipeId, photoKey, "맛있었다"));
        return photoKey;
    }

    /** 사진 없는 CookHistory. */
    public void saveCookHistory(Long recipeId) {
        cookHistoryRepository.save(CookHistory.create(recipeId, null, null));
    }

    /** 업로드까지 마친 뒤 연결까지 끝낸 Key. 연결이 실패하면 테스트가 아니라 픽스처가 잘못된 것이다. */
    private String attachedKey(Long ownerId, UploadPurpose purpose) {
        String objectKey = uploadedKey(ownerId, purpose);
        if (uploadService.attach(ownerId, objectKey, purpose) != AttachOutcome.ATTACHED) {
            throw new IllegalStateException("픽스처가 업로드를 연결하지 못했다: " + objectKey);
        }
        return objectKey;
    }

    private Recipe newRecipe(Long ownerId) {
        seedUser(ownerId);
        return Recipe.createManual(ownerId, "김치찌개", RecipeCategory.KOREAN, 30, 2, "조금 맵게");
    }
}
