spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starpick
    username: starpick
    password: starpick
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug