CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL UNIQUE REFERENCES users(user_id),
                                token_hash VARCHAR(64) NOT NULL UNIQUE,
                                expires_at TIMESTAMP NOT NULL,
                                created_at TIMESTAMP NOT NULL DEFAULT now()
);