-- 식사 알림: 사용자 설정(시간대는 jsonb), 기기별 푸시 토큰, 한 번만 시도하는 발송 기록.
create table notification_setting
(
    id         bigint generated by default as identity,
    user_id    bigint  not null,
    enabled    boolean not null,
    weekdays   text[]  not null default '{}',
    time_slots jsonb   not null default '[]',
    constraint pk_notification_setting primary key (id),
    constraint uk_notification_setting_user_id unique (user_id),
    constraint fk_notification_setting_user foreign key (user_id) references users (user_id),
    constraint ck_notification_setting_weekdays check (weekdays <@ array ['MONDAY', 'TUESDAY', 'WEDNESDAY',
        'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']::text[])
);

create table push_token
(
    id       bigint generated by default as identity,
    user_id  bigint       not null,
    token    text         not null,
    platform varchar(255) not null,
    active   boolean      not null,
    constraint pk_push_token primary key (id),
    constraint uk_push_token_token unique (token),
    constraint fk_push_token_user foreign key (user_id) references users (user_id),
    constraint ck_push_token_platform check (platform in ('IOS', 'ANDROID'))
);

create table push_log
(
    id            bigint generated by default as identity,
    user_id       bigint                      not null,
    push_token_id bigint                      not null,
    scheduled_at  timestamp(6) with time zone not null,
    status        varchar(255)                not null,
    opened_at     timestamp(6) with time zone,
    constraint pk_push_log primary key (id),
    constraint uk_push_log_token_scheduled_at unique (push_token_id, scheduled_at),
    constraint fk_push_log_user foreign key (user_id) references users (user_id),
    constraint fk_push_log_push_token foreign key (push_token_id) references push_token (id),
    constraint ck_push_log_status check (status in ('PROCESSING', 'SENT', 'FAILED'))
);
