create table user_ingredient (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(user_id),
    ingredient_id bigint not null references ingredient(id),
    created_at timestamptz not null default now(),
    constraint uk_user_ingredient unique (user_id, ingredient_id)
);
create index ix_user_ingredient_ingredient_id on user_ingredient (ingredient_id);
