create table users
(
    user_id              bigint generated by default as identity,
    service_terms_agreed boolean      not null,
    privacy_agreed       boolean      not null,
    marketing_agreed     boolean      not null,
    signup_completed_at  timestamp(6) not null,
    marketing_agreed_at  timestamp(6),
    last_login_provider  varchar(255),
    last_login_at        timestamp(6),
    created_at           timestamp(6) not null,
    deleted_at           timestamp(6),
    constraint pk_users primary key (user_id),
    constraint ck_users_last_login_provider
        check (last_login_provider in ('KAKAO', 'NAVER', 'GOOGLE', 'APPLE'))
);

create table profiles
(
    id                bigint generated by default as identity,
    user_id           bigint       not null,
    nickname          varchar(255) not null,
    profile_image_url varchar(255) not null,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    constraint pk_profiles primary key (id),
    constraint uk_profiles_user_id unique (user_id),
    constraint fk_profiles_user foreign key (user_id) references users (user_id)
);

create table social_credentials
(
    id         bigint generated by default as identity,
    user_id    bigint       not null,
    provider   varchar(255) not null,
    social_uid varchar(255) not null,
    email      varchar(255) not null,
    created_at timestamp(6) not null,
    constraint pk_social_credentials primary key (id),
    constraint uk_provider_social_uid unique (provider, social_uid),
    constraint uk_user_provider unique (user_id, provider),
    constraint ck_social_credentials_provider
        check (provider in ('KAKAO', 'NAVER', 'GOOGLE', 'APPLE')),
    constraint fk_social_credentials_user foreign key (user_id) references users (user_id)
);

create table recipe
(
    id                  bigint generated by default as identity,
    user_id             bigint       not null,
    title               varchar(255) not null,
    category_code       varchar(255) not null,
    registration_method varchar(255) not null,
    cover_image_key     varchar(255),
    cook_time_minutes   integer,
    servings            integer      not null,
    memo                text,
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null,
    constraint pk_recipe primary key (id),
    constraint ck_recipe_category_code
        check (category_code in
               ('KOREAN', 'WESTERN', 'CHINESE', 'JAPANESE', 'BUNSIK', 'ASIAN', 'OTHER')),
    constraint ck_recipe_registration_method
        check (registration_method in ('MANUAL', 'URL', 'IMAGE'))
);

create table recipe_ingredient
(
    id            bigint generated by default as identity,
    recipe_id     bigint       not null,
    ingredient_id bigint,
    name          varchar(255) not null,
    amount_text   varchar(255),
    display_order integer      not null,
    constraint pk_recipe_ingredient primary key (id),
    constraint fk_recipe_ingredient_recipe foreign key (recipe_id) references recipe (id)
);

create index idx_recipe_ingredient_recipe_id on recipe_ingredient (recipe_id);

create table recipe_step
(
    id            bigint generated by default as identity,
    recipe_id     bigint  not null,
    content       text    not null,
    display_order integer not null,
    constraint pk_recipe_step primary key (id),
    constraint fk_recipe_step_recipe foreign key (recipe_id) references recipe (id)
);

create index idx_recipe_step_recipe_id on recipe_step (recipe_id);

create table cook_history
(
    id        bigint generated by default as identity,
    recipe_id bigint                      not null,
    cooked_at timestamp(6) with time zone not null,
    photo_key varchar(255),
    memo      text,
    constraint pk_cook_history primary key (id),
    constraint uk_cook_history_photo_key unique (photo_key)
);

create index idx_cook_history_recipe_id on cook_history (recipe_id);

create table upload_object
(
    object_key  varchar(255) not null,
    user_id     bigint       not null,
    purpose     varchar(255) not null,
    attached_at timestamp(6),
    constraint pk_upload_object primary key (object_key),
    constraint ck_upload_object_purpose
        check (purpose in ('RECIPE_COVER', 'COOK_HISTORY_PHOTO', 'INGESTION_INPUT'))
);
