-- 사용자 문의와 관리자 답변. 답변은 문의당 1개라 같은 행에 두고, 상태는 answer 유무로 계산한다.
create table inquiry
(
    id              bigint generated by default as identity,
    user_id         bigint                      not null,
    type            varchar(255)                not null,
    title           varchar(255)                not null,
    content         text                        not null,
    attachment_keys text[]                      not null default '{}',
    answer          text,
    answered_at     timestamp(6) with time zone,
    created_at      timestamp(6) with time zone not null,
    constraint pk_inquiry primary key (id),
    constraint fk_inquiry_user foreign key (user_id) references users (user_id),
    constraint ck_inquiry_type check (type in ('RECIPE', 'SLOT', 'ACCOUNT', 'NOTIFICATION', 'BUG', 'ETC')),
    constraint ck_inquiry_attachment_keys check (cardinality(attachment_keys) <= 5),
    constraint ck_inquiry_answer check ((answer is null) = (answered_at is null))
);

-- 내 문의 목록: user_id 조건 + (created_at, id) 역순 정렬
create index idx_inquiry_user_id_created_at on inquiry (user_id, created_at, id);

-- CHECK 는 수정할 수 없어 지우고 다시 만든다.
alter table upload_object drop constraint ck_upload_object_purpose;
alter table upload_object
    add constraint ck_upload_object_purpose
        check (purpose in ('RECIPE_COVER', 'COOK_HISTORY_PHOTO', 'INGESTION_INPUT', 'INQUIRY_ATTACHMENT'));
