-- 보상형 광고 지급의 일일 집계·시청 세션·거래 이력. REWARDED_AD_SSV.md §6.

-- 사용자·KST 날짜별 지급/예약 횟수. quota_date 는 세션 발급 시각의 KST 날짜로 고정한다(§2.1).
create table ad_reward_daily_quota
(
    id             bigint generated by default as identity,
    user_id        bigint      not null,
    quota_date     date        not null,
    granted_count  integer     not null default 0,
    reserved_count integer     not null default 0,
    created_at     timestamptz not null default now(),
    constraint pk_ad_reward_daily_quota primary key (id),
    constraint fk_ad_reward_daily_quota_user foreign key (user_id) references users (user_id),
    constraint uk_ad_reward_daily_quota unique (user_id, quota_date),
    constraint ck_ad_reward_daily_quota_non_negative check (granted_count >= 0 and reserved_count >= 0),
    -- 일일 한도 3 은 현재 정책값이다(AdRewardProperties.dailyLimit). 한도를 바꾸면 이 제약도 새 migration 으로 바꾼다.
    constraint ck_ad_reward_daily_quota_limit check (granted_count + reserved_count <= 3)
);

-- 로그인 사용자와 연결된 시청 세션. id 는 애플리케이션이 발급하는 예측 불가능한 UUID다(§4.2).
create table ad_reward_session
(
    id                    uuid        not null,
    user_id               bigint      not null,
    request_id            varchar(255) not null,
    platform              varchar(255) not null,
    -- 콜백에서 실제로 대조할 광고 단위. 발급 시 플랫폼 설정으로 고정한다(§5.6).
    expected_ad_unit      varchar(255) not null,
    reward_type           varchar(255) not null default 'recipe_slot',
    reward_amount         integer     not null default 2,
    quota_date            date        not null,
    status                varchar(255) not null default 'PENDING',
    reason_code           varchar(255),
    created_at            timestamptz not null default now(),
    expires_at            timestamptz not null,
    verification_deadline timestamptz not null,
    granted_at            timestamptz,
    cancelled_at          timestamptz,
    constraint pk_ad_reward_session primary key (id),
    constraint fk_ad_reward_session_user foreign key (user_id) references users (user_id),
    -- (userId, requestId) 멱등 키(§4.2). 재시도는 같은 세션을 반환하고, 다른 플랫폼이면 409다.
    constraint uk_ad_reward_session_request unique (user_id, request_id),
    constraint ck_ad_reward_session_platform check (platform in ('ANDROID', 'IOS')),
    constraint ck_ad_reward_session_status check (status in ('PENDING', 'GRANTED', 'CANCELLED', 'EXPIRED', 'REJECTED')),
    constraint ck_ad_reward_session_reward_amount check (reward_amount > 0)
);

-- 날짜별 사용자당 진행 중 세션 1개 제한 확인과 상태 조회에 쓴다(§2.1, §4.1).
create index idx_ad_reward_session_user_quota_status on ad_reward_session (user_id, quota_date, status);

-- Google SSV 콜백 처리 이력. session_id/user_id 는 세션을 특정하지 못한 콜백에 한해 null 을 허용한다(§6).
create table ad_reward_transaction
(
    id                     bigint generated by default as identity,
    transaction_id         varchar(255) not null,
    session_id             uuid,
    user_id                bigint,
    status                 varchar(255) not null,
    reason_code            varchar(255),
    ad_unit                varchar(255) not null,
    reward_item            varchar(255) not null,
    received_reward_amount integer      not null,
    reward_event_at        timestamptz  not null,
    received_at            timestamptz  not null,
    processed_at           timestamptz  not null,
    granted_amount         integer      not null default 0,
    granted_at             timestamptz,
    constraint pk_ad_reward_transaction primary key (id),
    constraint fk_ad_reward_transaction_session foreign key (session_id) references ad_reward_session (id),
    constraint fk_ad_reward_transaction_user foreign key (user_id) references users (user_id),
    -- Google 거래 ID 는 전역 UNIQUE 다. 같은 거래의 재수신·동시 수신을 여기서 막는다(§7).
    constraint uk_ad_reward_transaction_transaction_id unique (transaction_id),
    constraint ck_ad_reward_transaction_status check (status in ('GRANTED', 'REJECTED')),
    -- 지급이면 금액이 양수이고 지급 시각이 있어야 하고, 거절이면 둘 다 비어야 한다.
    constraint ck_ad_reward_transaction_granted_amount check (
        (status = 'GRANTED' and granted_amount > 0 and granted_at is not null) or
        (status = 'REJECTED' and granted_amount = 0 and granted_at is null)
        )
);

-- 하나의 세션은 서로 다른 거래 ID가 와도 GRANTED 거래를 최대 한 번만 가질 수 있다(§6).
create unique index uk_ad_reward_transaction_granted_session
    on ad_reward_transaction (session_id)
    where status = 'GRANTED';

create index idx_ad_reward_transaction_user on ad_reward_transaction (user_id);
