create table user_custom_ingredient
(
    id         bigint generated by default as identity,
    user_id    bigint      not null,
    name       varchar(50) not null,
    created_at timestamptz not null default now(),
    constraint pk_user_custom_ingredient primary key (id),
    constraint fk_user_custom_ingredient_user foreign key (user_id) references users (user_id),
    constraint ck_user_custom_ingredient_name_not_blank check (btrim(name) <> '')
);

create index idx_user_custom_ingredient_user_id on user_custom_ingredient (user_id);
