alter table ingredient
    add column icon_key varchar(255);

update ingredient as i
set icon_key = mapping.icon_key
from (values
    ('MET001', 'pork'),
    ('MET002', 'pork'),
    ('MET003', 'pork'),
    ('MET004', 'pork'),
    ('MET005', 'beef'),
    ('MET006', 'beef'),
    ('MET007', 'beef'),
    ('MET008', 'chicken'),
    ('MET009', 'chicken'),
    ('MET010', 'duck'),
    ('MET011', 'bacon'),
    ('MET012', 'sausage'),
    ('SEA001', 'fish'),
    ('SEA002', 'salmon'),
    ('SEA003', 'fish'),
    ('SEA004', 'fish'),
    ('SEA005', 'fish'),
    ('SEA006', 'shrimp'),
    ('SEA007', 'squid'),
    ('SEA008', 'clam'),
    ('SEA009', 'clam'),
    ('SEA010', 'fish-cake'),
    ('SEA011', 'anchovy'),
    ('VEG001', 'onion'),
    ('VEG002', 'scallion'),
    ('VEG003', 'garlic'),
    ('VEG004', 'ginger'),
    ('VEG005', 'pepper'),
    ('VEG006', 'pepper'),
    ('VEG007', 'potato'),
    ('VEG008', 'sweet-potato'),
    ('VEG009', 'carrot'),
    ('VEG010', 'radish'),
    ('VEG011', 'lettuce'),
    ('VEG012', 'lettuce'),
    ('VEG013', 'perilla-leaf'),
    ('VEG014', 'spinach'),
    ('VEG015', 'zucchini'),
    ('VEG016', 'cucumber'),
    ('VEG017', 'tomato'),
    ('VEG018', 'bell-pepper'),
    ('VEG019', 'bean-sprouts'),
    ('VEG020', 'bean-sprouts'),
    ('VEG021', 'mushroom'),
    ('VEG022', 'lettuce'),
    ('VEG023', 'broccoli'),
    ('VEG024', 'corn'),
    ('SAU001', 'paste'),
    ('SAU002', 'paste'),
    ('SAU003', 'paste'),
    ('SAU004', 'paste'),
    ('SAU005', 'paste'),
    ('SAU006', 'sauce'),
    ('SAU007', 'sauce'),
    ('SAU008', 'sauce'),
    ('SAU009', 'sauce'),
    ('SAU010', 'sauce'),
    ('SAU011', 'sauce'),
    ('SAU012', 'liquid'),
    ('SAU013', 'liquid'),
    ('SAU014', 'liquid'),
    ('SAU015', 'oil'),
    ('SAU016', 'oil'),
    ('SAU017', 'oil'),
    ('SAU018', 'oil'),
    ('SAU019', 'basic-seasoning'),
    ('SAU020', 'basic-seasoning'),
    ('SAU021', 'basic-seasoning'),
    ('SAU022', 'seasoning-powder'),
    ('ETC001', 'egg'),
    ('ETC002', 'milk'),
    ('ETC003', 'cheese'),
    ('ETC004', 'butter'),
    ('ETC005', 'milk'),
    ('ETC006', 'milk'),
    ('ETC007', 'rice'),
    ('ETC008', 'flour'),
    ('ETC009', 'noodles'),
    ('ETC010', 'noodles'),
    ('ETC011', 'noodles'),
    ('ETC012', 'bread'),
    ('ETC013', 'tofu'),
    ('ETC014', 'seaweed'),
    ('ETC015', 'box'),
    ('ETC016', 'box'),
    ('ETC017', 'seaweed'),
    ('ETC018', 'kimchi')
) as mapping(code, icon_key)
where i.code = mapping.code;

alter table ingredient
    alter column icon_key set not null;

insert into ingredient (code, name, category_code, aliases, icon_key) values
('MET013', '쇠고기(차돌박이)', 'MEAT',      '{"차돌박이","쇠고기","소고기"}', 'beef'),
('SEA012', '명란',             'SEAFOOD',   '{}',                               'pollock-roe'),
('SEA013', '굴',               'SEAFOOD',   '{}',                               'oyster'),
('SEA014', '꽃게',             'SEAFOOD',   '{}',                               'crab'),
('SEA016', '미역',             'SEAFOOD',   '{}',                               'seaweed'),
('VEG025', '가지',             'VEGETABLE', '{}',                               'eggplant'),
('VEG026', '쪽파',             'VEGETABLE', '{}',                               'scallion'),
('VEG027', '양상추',           'VEGETABLE', '{}',                               'lettuce'),
('SAU023', '카레가루',         'SAUCE',     '{}',                               'seasoning-powder'),
('SAU024', '치킨스톡',         'SAUCE',     '{}',                               'seasoning-powder'),
('SAU025', '다시다',           'SAUCE',     '{}',                               'seasoning-powder'),
('SAU026', '올리고당/물엿',    'SAUCE',     '{"올리고당","물엿"}',             'liquid'),
('ETC019', '전분가루',         'ETC',       '{}',                               'flour'),
('ETC020', '메추리알',         'ETC',       '{}',                               'egg'),
('ETC021', '사과',             'ETC',       '{}',                               'apple'),
('ETC022', '배',               'ETC',       '{}',                               'pear'),
('ETC023', '레몬',             'ETC',       '{}',                               'lemon');
