create table ingestion_job
(
    id               bigint generated by default as identity,
    user_id          bigint                      not null,
    source_type      varchar(255)                not null,
    input_url        varchar(2048),
    input_image_keys text[],
    status           varchar(255)                not null,
    result           jsonb,
    failure_code     varchar(255),
    attempt          integer                     not null,
    created_at       timestamp(6) with time zone not null,
    started_at       timestamp(6) with time zone,
    expires_at       timestamp(6) with time zone,
    consumed_at      timestamp(6) with time zone,
    constraint pk_ingestion_job primary key (id),
    constraint fk_ingestion_job_user
        foreign key (user_id) references users (user_id),
    constraint ck_ingestion_job_source_type
        check (source_type in ('IMAGE', 'YOUTUBE', 'INSTAGRAM')),
    constraint ck_ingestion_job_status
        check (status in ('QUEUED', 'PROCESSING', 'RESULT_READY', 'FAILED', 'EXPIRED')),
    constraint ck_ingestion_job_failure_code
        check (failure_code in ('SOURCE_UNAVAILABLE', 'CONTENT_NOT_RECOGNIZED', 'PROCESSING_FAILED')),
    constraint ck_ingestion_job_input
        check ((source_type = 'IMAGE'
                and input_url is null
                and input_image_keys is not null
                and cardinality(input_image_keys) >= 1)
            or (source_type <> 'IMAGE'
                and input_url is not null
                and input_image_keys is null))
);

create index idx_ingestion_job_queued on ingestion_job (id) where status = 'QUEUED';
create index idx_ingestion_job_user_created_at on ingestion_job (user_id, created_at);
